use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var_os("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("methods.rs");
    
    // Generate a simple placeholder content for methods.rs
    let methods_content = r#"
        // This file is auto-generated by build.rs
        pub fn placeholder() {
            println!("This is a placeholder function");
        }
    "#;

    fs::write(&dest_path, methods_content).unwrap();
    
    println!("cargo:rerun-if-changed=build.rs");
}